#!/bin/bash -xe

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

if [[ "$#" -gt 0 ]] ; then
  $DOCKER_COMPOSE run --rm $(power_dnsex_env) web "$@"
else
  $DOCKER_COMPOSE run --service-ports --rm $(power_dnsex_env) web iex -S mix do hex.info
fi
